# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Entangled WASM Rust demo

watch:
  - docs

plugins:
  - search
  - entangled
#  - macros:
#      include_dir: include
#  - bibtex:
#      bib_file: "docs/references.bib"

markdown_extensions:
   - pymdownx.superfences
   - admonition
   - def_list
   - footnotes
   - attr_list
   - md_in_html
   - pymdownx.details
   - pymdownx.arithmatex:
       generic: true
   - toc:
       permalink: true
   - pymdownx.emoji:
       emoji_index: !!python/name:material.extensions.emoji.twemoji
       emoji_generator: !!python/name:material.extensions.emoji.to_svg
   - pymdownx.highlight:
       anchor_linenums: true
       line_spans: __span
       pygments_lang_class: true
   - pymdownx.inlinehilite
   - pymdownx.snippets

theme:
  name: material
  features:
    - content.code.annotate
  palette:
      # Palette toggle for light mode
      - scheme: default
        primary: orange
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        primary: pink
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

extra_javascript:
    - js/mathjax.js
    - js/wasm_entangled_demo.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
